[package]
name = "shosearch"
version = "0.1.0"
authors = ["aol1306 <jdzieciatko@gmail.com>"]
edition = "2018"

[dependencies]
mongodb = "0.3.12"
reqwest = "0.9.9"
serde_json = "1.0"
simplelog = "*"
log = "*"
argparse = "*"
url = "*"
